import type { PlayerStats } from "./types"

export interface SubmarineTier {
  tier: number
  name: string
  description: string
  baseStats: PlayerStats
  upgradeCost: {
    nickel: number
    cobalt: number
    copper: number
    manganese: number
    tokens: number
  }
  color: string
  specialAbility?: string
}

export const SUBMARINE_TIERS: SubmarineTier[] = [
  {
    tier: 1,
    name: "Nautilus I",
    description: "Basic exploration submarine with limited storage capacity.",
    baseStats: {
      health: 100,
      energy: 100,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 100, cobalt: 50, copper: 50, manganese: 25 },
      depth: 1000,
      speed: 1,
      miningRate: 1,
      tier: 1,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 0)),
      cobalt: Math.floor(25 * Math.pow(1.3, 0)),
      copper: Math.floor(25 * Math.pow(1.3, 0)),
      manganese: Math.floor(15 * Math.pow(1.3, 0)),
      tokens: Math.floor(100 * Math.pow(1.5, 0)),
    },
    color: "#fbbf24",
  },
  {
    tier: 2,
    name: "Nautilus II",
    description: "Improved submarine with enhanced storage and durability.",
    baseStats: {
      health: 125,
      energy: 120,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 150, cobalt: 75, copper: 75, manganese: 40 },
      depth: 1200,
      speed: 1.1,
      miningRate: 1.2,
      tier: 2,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 1)),
      cobalt: Math.floor(25 * Math.pow(1.3, 1)),
      copper: Math.floor(25 * Math.pow(1.3, 1)),
      manganese: Math.floor(15 * Math.pow(1.3, 1)),
      tokens: Math.floor(100 * Math.pow(1.5, 1)),
    },
    color: "#f59e0b",
  },
  {
    tier: 3,
    name: "Abyssal Explorer",
    description: "Specialized deep-sea submarine with reinforced hull.",
    baseStats: {
      health: 150,
      energy: 140,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 200, cobalt: 100, copper: 100, manganese: 60 },
      depth: 1500,
      speed: 1.2,
      miningRate: 1.4,
      tier: 3,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 2)),
      cobalt: Math.floor(25 * Math.pow(1.3, 2)),
      copper: Math.floor(25 * Math.pow(1.3, 2)),
      manganese: Math.floor(15 * Math.pow(1.3, 2)),
      tokens: Math.floor(100 * Math.pow(1.5, 2)),
    },
    color: "#d97706",
  },
  {
    tier: 4,
    name: "Mariana Miner",
    description: "Heavy-duty mining submarine with expanded cargo holds.",
    baseStats: {
      health: 175,
      energy: 160,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 300, cobalt: 150, copper: 150, manganese: 80 },
      depth: 1800,
      speed: 1.3,
      miningRate: 1.6,
      tier: 4,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 3)),
      cobalt: Math.floor(25 * Math.pow(1.3, 3)),
      copper: Math.floor(25 * Math.pow(1.3, 3)),
      manganese: Math.floor(15 * Math.pow(1.3, 3)),
      tokens: Math.floor(100 * Math.pow(1.5, 3)),
    },
    color: "#b45309",
  },
  {
    tier: 5,
    name: "Hydrothermal Hunter",
    description: "Advanced submarine with heat-resistant plating for volcanic regions.",
    baseStats: {
      health: 200,
      energy: 180,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 400, cobalt: 200, copper: 200, manganese: 100 },
      depth: 2200,
      speed: 1.4,
      miningRate: 1.8,
      tier: 5,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 4)),
      cobalt: Math.floor(25 * Math.pow(1.3, 4)),
      copper: Math.floor(25 * Math.pow(1.3, 4)),
      manganese: Math.floor(15 * Math.pow(1.3, 4)),
      tokens: Math.floor(100 * Math.pow(1.5, 4)),
    },
    color: "#92400e",
  },
  {
    tier: 6,
    name: "Pressure Pioneer",
    description: "Cutting-edge submarine designed for extreme depths.",
    baseStats: {
      health: 250,
      energy: 220,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 500, cobalt: 250, copper: 250, manganese: 125 },
      depth: 2600,
      speed: 1.5,
      miningRate: 2.0,
      tier: 6,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 5)),
      cobalt: Math.floor(25 * Math.pow(1.3, 5)),
      copper: Math.floor(25 * Math.pow(1.3, 5)),
      manganese: Math.floor(15 * Math.pow(1.3, 5)),
      tokens: Math.floor(100 * Math.pow(1.5, 5)),
    },
    color: "#78350f",
    specialAbility: "Pressure Resistance: Immune to depth damage",
  },
  {
    tier: 7,
    name: "Quantum Diver",
    description: "Experimental submarine with quantum-stabilized hull.",
    baseStats: {
      health: 300,
      energy: 260,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 650, cobalt: 325, copper: 325, manganese: 160 },
      depth: 3000,
      speed: 1.6,
      miningRate: 2.2,
      tier: 7,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 6)),
      cobalt: Math.floor(25 * Math.pow(1.3, 6)),
      copper: Math.floor(25 * Math.pow(1.3, 6)),
      manganese: Math.floor(15 * Math.pow(1.3, 6)),
      tokens: Math.floor(100 * Math.pow(1.5, 6)),
    },
    color: "#1e40af",
    specialAbility: "Quantum Scanning: Reveals hidden resource nodes",
  },
  {
    tier: 8,
    name: "Titan Explorer",
    description: "Massive submarine with reinforced titanium hull.",
    baseStats: {
      health: 350,
      energy: 300,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 800, cobalt: 400, copper: 400, manganese: 200 },
      depth: 3500,
      speed: 1.7,
      miningRate: 2.4,
      tier: 8,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 7)),
      cobalt: Math.floor(25 * Math.pow(1.3, 7)),
      copper: Math.floor(25 * Math.pow(1.3, 7)),
      manganese: Math.floor(15 * Math.pow(1.3, 7)),
      tokens: Math.floor(100 * Math.pow(1.5, 7)),
    },
    color: "#1e3a8a",
    specialAbility: "Titanium Hull: 50% damage reduction",
  },
  {
    tier: 9,
    name: "Void Stalker",
    description: "Stealth submarine with advanced cloaking technology.",
    baseStats: {
      health: 400,
      energy: 340,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 950, cobalt: 475, copper: 475, manganese: 240 },
      depth: 4000,
      speed: 1.8,
      miningRate: 2.6,
      tier: 9,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 8)),
      cobalt: Math.floor(25 * Math.pow(1.3, 8)),
      copper: Math.floor(25 * Math.pow(1.3, 8)),
      manganese: Math.floor(15 * Math.pow(1.3, 8)),
      tokens: Math.floor(100 * Math.pow(1.5, 8)),
    },
    color: "#312e81",
    specialAbility: "Stealth Mode: Invisible to other players for 30 seconds",
  },
  {
    tier: 10,
    name: "Kraken Hunter",
    description: "Legendary submarine designed to hunt the deepest creatures.",
    baseStats: {
      health: 500,
      energy: 400,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 1200, cobalt: 600, copper: 600, manganese: 300 },
      depth: 5000,
      speed: 2.0,
      miningRate: 3.0,
      tier: 10,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 9)),
      cobalt: Math.floor(25 * Math.pow(1.3, 9)),
      copper: Math.floor(25 * Math.pow(1.3, 9)),
      manganese: Math.floor(15 * Math.pow(1.3, 9)),
      tokens: Math.floor(100 * Math.pow(1.5, 9)),
    },
    color: "#581c87",
    specialAbility: "Kraken Sonar: Detects all resources within 500m radius",
  },
  {
    tier: 11,
    name: "Plasma Forge",
    description: "Energy-powered submarine with plasma mining capabilities.",
    baseStats: {
      health: 600,
      energy: 500,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 1400, cobalt: 700, copper: 700, manganese: 350 },
      depth: 6000,
      speed: 2.2,
      miningRate: 3.4,
      tier: 11,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 10)),
      cobalt: Math.floor(25 * Math.pow(1.3, 10)),
      copper: Math.floor(25 * Math.pow(1.3, 10)),
      manganese: Math.floor(15 * Math.pow(1.3, 10)),
      tokens: Math.floor(100 * Math.pow(1.5, 10)),
    },
    color: "#7c2d12",
    specialAbility: "Plasma Mining: Mines 2x faster for rare resources",
  },
  {
    tier: 12,
    name: "Dimensional Rift",
    description: "Interdimensional submarine that bends space-time.",
    baseStats: {
      health: 750,
      energy: 650,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 1600, cobalt: 800, copper: 800, manganese: 400 },
      depth: 7500,
      speed: 2.5,
      miningRate: 3.8,
      tier: 12,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 11)),
      cobalt: Math.floor(25 * Math.pow(1.3, 11)),
      copper: Math.floor(25 * Math.pow(1.3, 11)),
      manganese: Math.floor(15 * Math.pow(1.3, 11)),
      tokens: Math.floor(100 * Math.pow(1.5, 11)),
    },
    color: "#be123c",
    specialAbility: "Dimensional Shift: Teleport to any location instantly",
  },
  {
    tier: 13,
    name: "Cosmic Voyager",
    description: "Submarine powered by cosmic energy from distant stars.",
    baseStats: {
      health: 900,
      energy: 800,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 1800, cobalt: 900, copper: 900, manganese: 450 },
      depth: 9000,
      speed: 2.7,
      miningRate: 4.2,
      tier: 13,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 12)),
      cobalt: Math.floor(25 * Math.pow(1.3, 12)),
      copper: Math.floor(25 * Math.pow(1.3, 12)),
      manganese: Math.floor(15 * Math.pow(1.3, 12)),
      tokens: Math.floor(100 * Math.pow(1.5, 12)),
    },
    color: "#9333ea",
    specialAbility: "Cosmic Energy: Regenerates energy 3x faster",
  },
  {
    tier: 14,
    name: "Omega Destroyer",
    description: "The penultimate submarine with reality-warping technology.",
    baseStats: {
      health: 1200,
      energy: 1000,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 2000, cobalt: 1000, copper: 1000, manganese: 500 },
      depth: 12000,
      speed: 3.0,
      miningRate: 4.8,
      tier: 14,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 13)),
      cobalt: Math.floor(25 * Math.pow(1.3, 13)),
      copper: Math.floor(25 * Math.pow(1.3, 13)),
      manganese: Math.floor(15 * Math.pow(1.3, 13)),
      tokens: Math.floor(100 * Math.pow(1.5, 13)),
    },
    color: "#dc2626",
    specialAbility: "Reality Warp: Can mine multiple nodes simultaneously",
  },
  {
    tier: 15,
    name: "Leviathan",
    description: "The ultimate deep-sea mining vessel, unmatched in all aspects.",
    baseStats: {
      health: 1500,
      energy: 1500,
      capacity: { nickel: 0, cobalt: 0, copper: 0, manganese: 0 },
      maxCapacity: { nickel: 2500, cobalt: 1250, copper: 1250, manganese: 625 },
      depth: 15000,
      speed: 3.5,
      miningRate: 5.0,
      tier: 15,
    },
    upgradeCost: {
      nickel: Math.floor(50 * Math.pow(1.3, 14)),
      cobalt: Math.floor(25 * Math.pow(1.3, 14)),
      copper: Math.floor(25 * Math.pow(1.3, 14)),
      manganese: Math.floor(15 * Math.pow(1.3, 14)),
      tokens: Math.floor(100 * Math.pow(1.5, 14)),
    },
    color: "#7e22ce",
    specialAbility: "Omnimining: Can mine all resources simultaneously at 2x rate",
  },
]

export function getSubmarineByTier(tier: number): SubmarineTier {
  return SUBMARINE_TIERS.find((sub) => sub.tier === tier) || SUBMARINE_TIERS[0]
}

export function getNextSubmarineTier(currentTier: number): SubmarineTier | null {
  if (currentTier >= SUBMARINE_TIERS.length) return null
  return SUBMARINE_TIERS.find((sub) => sub.tier === currentTier + 1) || null
}
