// TEMPORARY CONFIG FOR TESTING - REMOVE IN PRODUCTION
export const TEMP_CONFIG = {
  MORALIS_API_KEY:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6Ijc4MWNmZTU2LWRmZTQtNGIwMS1hZDBlLTg1NDI1NjM0NjFlZiIsIm9yZ0lkIjoiNDUxMDg0IiwidXNlcklkIjoiNDY0MTMwIiwidHlwZUlkIjoiNjc2MzNmZmUtZmUxOS00MDk3LWFkYTAtYjM5NDFlM2Y1NWNlIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3NDkxMTEwNDQsImV4cCI6NDkwNDg3MTA0NH0.vHxMikx-DzgJ8M3cbzWgKUlz9_1qA4zB9ShrVepMU4M",
  SUPABASE_URL: "https://crwkgwghgkypxcoxefid.supabase.co",
  SUPABASE_ANON_KEY:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyd2tnd2doZ2t5cHhjb3hlZmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTAwMTksImV4cCI6MjA2NDY4NjAxOX0.gW1d_fcNW24EUU0HZOrc70FlGyjpwcCTKDGB-MjRcxM",
  SUPABASE_SERVICE_KEY:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyd2tnd2doZ2t5cHhjb3hlZmlkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTExMDAxOSwiZXhwIjoyMDY0Njg2MDE5fQ.AZnmLQN7AQR43owZ_vPyVm5lnI39bTrp97f-xRamqQc",
}

// Helper function to get config values
export function getConfig() {
  return {
    MORALIS_API_KEY: process.env.NEXT_PUBLIC_MORALIS_API_KEY || TEMP_CONFIG.MORALIS_API_KEY,
    SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || TEMP_CONFIG.SUPABASE_URL,
    SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || TEMP_CONFIG.SUPABASE_ANON_KEY,
    SUPABASE_SERVICE_KEY: process.env.SUPABASE_SERVICE_KEY || TEMP_CONFIG.SUPABASE_SERVICE_KEY,
  }
}
